object Versions {
    const val coreAndroidX = "1.8.0"
    const val lifeCycleRuntime = "2.3.1"
    const val activityCompose = "1.5.1"
    const val composeNav = "2.5.3"
    const val composeBom = "2022.10.00"
    const val composeUi = "ui"
    const val composeGraphics = "ui-graphics"
    const val composeUiToolingPreview = "ui-tooling-preview"
    const val composeMaterial3 = "material3"
    const val junit = "4.13.2"
    const val androidTestJUnit = "1.1.3"
    const val androidTestEspresso = "3.4.0"
    const val androidTestComposeBom = "2022.10.00"
    const val androidTestComposeUi = "ui-test-junit4"
    const val debugComposeUiTooling = "ui-tooling"
    const val debugComposeUiTestManifest = "ui-test-manifest"
    const val hilt = "2.44"
    const val workRuntime = "2.8.1"
    const val room = "2.5.1"
    const val gson = "2.10.1"
    const val ktor = "2.3.0"
    const val hiltNavigationComposeVersion = "1.0.0"
    const val datastoreVersion = "1.0.0"
}